### ISSUE TITLE
Sync wtih Google calendar‎  

### ISSUE THREAD

**Issue by rezakamalifard** [ilius/starcal#6]
Is there any way to sync starcal events with Google cal ?

**Comment by k1-hedayati** [comment]
I think you don't need to worry about poor Iranians, it's their problem. Implement synchronization in your app, Iranians can find a way for bypass blocking (as they always do).
If you're so interested in helping them you can create another module/service/app for this matter.
So please don't combine two separate issues into one ;)

**Comment by ilius** [comment]
For technical reasons, a good implementation of Google calendar sync is much more challenging than you think: because Google cal use iCalendar, and iCalendar is too old, messy and complicated, and it only supports Gregorian, while StarCalendar aims to support multiple calendars equally (so it uses it's own event structure & format which was also very hard to design & implement). So it's almost impossible to write a perfect implementation, and very hard to write a good implementation (which I'm trying to do sometimes). So if there is not enough use for this feature for us (Iranians), there is not enough motivation to do it.

I'm also thinking of writing a StarCalendar event API service as a replacement for Google calendar, but without any web interface, only a service to interact with desktop application.
That might be easier (and will be safer to use) than Google calendar for this international calendar.

So there are no *separate issues*, dear Keyvan. Everything is related to everything :)

**Comment by k1-hedayati** [comment]
Well, I wasn't aware of Google calender issues and thought the problem is blocked users. Writing API  web service is great idea. I still insists those two issues were separate ;)
Thanks for explanation

**Comment by ilius** [comment]
I started the project: https://github.com/ilius/starcal-server
Although we have a long way to Go! I hope I can prepare a working release in a year
I'm gonna need a host (AWS maybe) and a domain (starcal.org is registered but not used).
Any helps are appreciated.
