### ISSUE TITLE
Why supported Python versions are hardcoded?

### ISSUE THREAD

**Issue by hedayat** [ilius/starcal#66]
Isn't the code expected to be compatible with 3.x python versions?  Each time a new Python versions comes out, it should be explicitly added to the list of supported versions, which I'm not sure is logical. Is Python expected to break backward compatibility in its minor releases?

Thanks

**Comment by ilius** [comment]
It has happened once in Python 3.7.
A piece of code and a library that was working with 3.6.x, was broken with 3.7.0.
And since I don't (and don't plan to) maintain libraries used as dependencies, it was broken for quite a while.

The Python codes don't check the minor version.
Only installer scripts do.
If you maintain a distro package or want to test a new Python beta version, you can either modify the installer, or avoid using installers altogether (install dependencies manually and just run the program).

**Comment by hedayat** [comment]
Thanks for the explanation.

Yes, I maintain starcal for Fedora, and I do modify the installer each time a new Python version comes out. Just wondered if it can be omitted. So, I'll continue doing this going forward. 

Anyway, starcal is at least syntactically compatible with Python 3.10.
